### [CVE-2015-3206](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-3206)
![](https://img.shields.io/static/v1?label=Product&message=n%2Fa&color=blue)
![](https://img.shields.io/static/v1?label=Version&message=%3D%20n%2Fa%20&color=brighgreen)
![](https://img.shields.io/static/v1?label=Vulnerability&message=n%2Fa&color=brighgreen)

### Description

The checkPassword function in python-kerberos does not authenticate the KDC it attempts to communicate with, which allows remote attackers to cause a denial of service (bad response), or have other unspecified impact by performing a man-in-the-middle attack.

### POC

#### Reference
- https://github.com/apple/ccs-pykerberos/issues/31

#### Github
No PoCs found on GitHub currently.

